exclude_paths:
  - tmp
  - vendor

detectors:
  FeatureEnvy:
    exclude:
      - "Pennyworth::Loaders::HTMX#fetch"
      - "Pennyworth::Loaders::RFC#fetch"
      - "Pennyworth::Loaders::Rodauth#fetch"
  LongParameterList:
    enabled: false
  ModuleInitialize:
    exclude:
      - "Pennyworth::Models"
  TooManyStatements:
    exclude:
      - "Pennyworth::CLI::Shell#cli"
