---
detectors:
  DuplicateMethodCall:
    exclude:
    - Pennyworth::CLI#install
  IrresponsibleModule:
    enabled: false
  TooManyStatements:
    exclude:
    - initialize
    - Pennyworth::CLI#install
    - Pennyworth::CLI#string
