inherit_gem:
  caliber: config/all.yml

Metrics/AbcSize:
  Exclude:
    - "lib/pennyworth/cli/shell.rb"
Metrics/CyclomaticComplexity:
  AllowedMethods:
    - act_on
Metrics/MethodLength:
  Exclude:
    - "lib/pennyworth/cli/shell.rb"
Metrics/PerceivedComplexity:
  AllowedMethods:
    - act_on
