language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - jruby
  - rbx-2
before_install: rm -f Gemfile.lock
script: bundle exec rspec spec
notifications:
  email: false
  campfire:
    rooms:
      - secure: "hOJbOGKAvvtvImFr42t4dz/aueexHfuAG317GKeMhqz5aYTZmAy3WE043pF1\nD7fIoL8TUu9K+oOwg4pa48rnT2b0+tgV5tp7/L8AQ6/rCwO/gBltlCV9Myit\nMdcEhfNrNZ7m3Fb/j8QndX2EzhTrAHVbL0ZTSHcMxbK6c/VXCdA="
