language: ruby
rvm:
  - 1.9.2
  - 1.9.3
gemfile:
  - gemfiles/rails-3.1.x.gemfile
  - gemfiles/rails-3.2.x.gemfile
script: bundle exec rspec spec
notifications:
  email: false
  campfire:
    rooms:
      - secure: "hOJbOGKAvvtvImFr42t4dz/aueexHfuAG317GKeMhqz5aYTZmAy3WE043pF1\nD7fIoL8TUu9K+oOwg4pa48rnT2b0+tgV5tp7/L8AQ6/rCwO/gBltlCV9Myit\nMdcEhfNrNZ7m3Fb/j8QndX2EzhTrAHVbL0ZTSHcMxbK6c/VXCdA="
